services:
  dev:
    build: .
    container_name: visual-dataframe
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:
      - .:/workspace
    # command: jupyter notebook --allow-root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host